### ISSUE TITLE
Update KX examples in Cloud Provider Apps & General Apps

### ISSUE THREAD

**Issue by metral** [pulumi/kubernetes-guides#34]
Some of the KX code examples are using an old spec that takes a name and the pod spec. We've since moved to a podbuilder spec that is simplified, so we need to update the code samples to reflect the latest API

**Comment by lblackstone** [comment]
Can you link me to specific examples? I didn't see any outdated uses when I searched for "kx".

**Comment by metral** [comment]
For example in the docs we have:

https://www.pulumi.com/docs/guides/crosswalk/kubernetes/apps/#create-a-deployment-with-a-secret

```
// Create a KX Deployment from the KX PodBuilder by transforming it into a DeploymentSpec.
// The deployment use database credentials as environment variables.
const nginxDeployment = new kx.Deployment(appName, {
    spec: nginxPB.asDeploymentSpec({replicas: 1})
}, { provider: provider });
```

which comes from 

https://github.com/pulumi/kubernetes-guides/blob/a01cd24cec5f6c05464df54e9fb28a498bda799f/apps/deployment-secret/index.ts#L88-L93

**Comment by metral** [comment]
Same with https://www.pulumi.com/docs/guides/crosswalk/kubernetes/apps/#deploy-a-job
